Ajout du formulaire pour les CV
zankia/CVTheque pull request #5
Opened 2017-01-16 16:28 UTC by antoineguillory

2017-01-16 18:39 UTC, zankia requested changes

2017-01-16 18:39 UTC, zankia commented on controller/CV.php
> +            && isset($_POST['ville']) && isset($_POST['domaine']) ){
Le candidat n'est peut être pas obligé de tout renseigner, si?

2017-01-16 18:39 UTC, zankia commented on view/resources/page/CV/cv.php
> +            </form>
Tu peux rajouter required si c'est requis (coté client)
Serait-il possible de le faire en HTML (et indenté) ?

2017-01-16 19:35 UTC, antoineguillory commented on controller/CV.php
> +            && isset($_POST['ville']) && isset($_POST['domaine']) ){
Ok bah dit moi quels champs sont obligatoires car c'est pas vraiment marqué dans l'énoncé. Évidement j'ai pas encore traité les remarques et j'en ai pas fait une obligation

2017-01-16 20:07 UTC, zankia commented on controller/CV.php
> +            && isset($_POST['ville']) && isset($_POST['domaine']) ){
nom, prénom, au moins un numero de telephone, c'est deja un bon début.
Et du coup, domaine, on le garde ou pas?

2017-01-17 20:14 UTC, antoineguillory commented on controller/CV.php
> +            && isset($_POST['ville']) && isset($_POST['domaine']) ){
Ok je modifie ça demain du coup. On pourra en discuter, pour le domaine ça peut être intéressant, mais faut qu'on en fasse quelque chose si on le garde

2017-01-18 10:10 UTC, merged